let cart=[{  
    id:1,
    name: "Perfume",
    desc: "",
    price: "$100",
    category:"Cosmetics",
    imageURL:"images/perfume.jpg" ,
        },{
    id:2,
    name: "Lipstick",
    desc: "",
    price: "$25",
    category:"Cosmetics",
    imageURL:"images/lipstick.jpg" ,
        },{
    id:3,
    name: "Apple Airpods",
    desc: "",
    price: "$100",
    category:"Technology",
    imageURL:"images/airpods.jpg" ,
        },
        {
    id:4,
    name: "SmartWatch",
    desc: "",
    price: "$200",
    category:"Technology",
    imageURL:"images/smartWatch.jpg" ,
        }];